@domain_remote =  -
@domain_local =  http://localhost:4000/dev

@domain = {{domain_local}}

### 200 OK
GET {{domain}}/api/fans

### 200 OK
GET {{domain}}/api/fans/80D3215D-F761-46CC-A71B-06F5529C17DC

### 400 Bad Request
GET {{domain}}/api/fans/234234