@domain_remote =  -
@domain_local =  http://localhost:4000/dev

@domain = {{domain_local}}

### 200 OK
GET {{domain}}/api/fans

### 200 OK
GET {{domain}}/api/fans?category=Ceiling+Fans

### 200 OK - Empty array returned
GET {{domain}}/api/fans?category=Ceiling+Fans

### 200 OK
GET {{domain}}/api/fans?category=Ceiling+Fans

### 200 OK
POST {{domain}}/api/contact-details

{
  "name": "Diana",
  "surname": "Prince",
  "email": "dianaprince@gmail.com",
  "categoryId": "2"
}