@domain_remote =  -
@domain_local =  http://localhost:4000/dev

@domain = {{domain_local}}

### 200 OK
GET {{domain}}/api/fans

### 200 OK
GET {{domain}}/api/fans?category=Ceiling+Fans&rpm=300&cfm=4800&sweep=1750

### 400 Bad Request - Has to have all parameters
GET {{domain}}/api/fans?category=Ceiling+Fans
