service: template-project

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  region: af-south-1
  lambdaHashingVersion: 20201221
  timeout: 20
  environment:
    stage: ${self:custom.myStage}

custom:
  myStage: ${opt:stage, 'dev'}
  serverless-offline:
    httpPort: 4000
    websocketPort: 4001
    lambdaPort: 4002

functions:
  allFans:
    name: ${self:service}-AllFans
    handler: functions/fans-controller.getAllFans
    events:
      - http:
          path: api/fans
          method: get
          cors: true
  fansByID:
    name: ${self:service}-fansByID
    handler: functions/fans-controller.getFanByID
    events:
      - http:
          path: api/fans/{id}
          method: get
          cors: true

plugins:
  - serverless-offline
