service: template-project

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  region: af-south-1
  lambdaHashingVersion: 20201221
  timeout: 20
  environment:
    stage: ${self:custom.myStage}

custom:
  myStage: ${opt:stage, 'dev'}
  serverless-offline:
    httpPort: 4000
    websocketPort: 4001
    lambdaPort: 4002

functions:
  testFunction1:
    name: ${self:service}-testFunction
    handler: functions/test.testFunction
    events:
      - http:
          path: api/mock
          method: get
          cors: true

plugins:
  - serverless-offline
