USE `OnlyFansDB`;

DROP PROCEDURE IF EXISTS `pGetFanById`;
DROP PROCEDURE IF EXISTS `pGetFansByMaxRPM`;
DROP PROCEDURE IF EXISTS `pGetFansByMaxCFM`;
DROP PROCEDURE IF EXISTS `pGetFansByMaxSpan`;
DROP PROCEDURE IF EXISTS `pGetFansByCategory`;
DROP PROCEDURE IF EXISTS `pGetFansByAtributes`;

DELIMITER //
CREATE PROCEDURE `pGetFanById` (IN ID VARCHAR(32))
BEGIN
  IF IS_UUID(ID) THEN
    BEGIN
      SELECT BIN_ID = UUID_TO_BIN(ID);
 
      SELECT *
      FROM `vFullFans` AS `F` 
      WHERE `F`.`FanId` = BIN_ID;
    END;
  END IF;
END//

DELIMITER //
CREATE PROCEDURE `pGetFansByMaxRPM` (IN RPM INT)
BEGIN
  SELECT *
  FROM `Fan` AS `F` 
  WHERE `F`.`FanRPM` <= RPM;
END//

DELIMITER //
CREATE PROCEDURE `pGetFansByMaxCFM` (IN CFM INT)
BEGIN
  SELECT *
  FROM `Fan` AS `F` 
  WHERE `F`.`FanCFM` <= CFM;
END//

DELIMITER //
CREATE PROCEDURE `pGetFansByMaxSpan` (IN SPAN INT)
BEGIN
  SELECT *
  FROM `Fan` AS `F` 
  WHERE `F`.`FanSpanMM` <= SPAN;
END//

DELIMITER //
CREATE PROCEDURE `pGetFansByCategory` (IN CATEGORY_NAME VARCHAR(50))
BEGIN
  SELECT *
  FROM `vFullFans` AS `F` 
  WHERE `F`.`FanCategoryName` = CATEGORY_NAME;
END//

DELIMITER //
CREATE PROCEDURE `pGetFansByAtributes` (IN RPM INT, IN CFM INT, IN SPAN INT, IN CATEGORY_NAME VARCHAR(50))
BEGIN
  SELECT *
  FROM `vFullFans` AS `F` 
  WHERE `F`.`FanRPM` <= RPM
  AND `F`.`FanCFM` <= CFM
  AND `F`.`FanSpanMM` <= SPAN
  AND `F`.`FanCategoryName` = CATEGORY_NAME;
END//

DELIMITER ;
